# Generated by Django 4.1.4 on 2022-12-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.CharField(max_length=11)),
                ("recorded_on", models.DateField()),
                ("max_temperature", models.IntegerField()),
                ("min_temperature", models.IntegerField()),
                ("amt_of_precipitation", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="YieldData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "harvested_in_year",
                    models.IntegerField(
                        help_text="Year in which the harvesting data was collected"
                    ),
                ),
                (
                    "amount_harvested",
                    models.IntegerField(
                        help_text="total harvested corn grain yield in the United States measured in 1000s of megatons"
                    ),
                ),
            ],
        ),
    ]
