# Generated by Django 4.1.4 on 2022-12-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherDataStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.IntegerField()),
                ("recorded_on", models.IntegerField()),
                ("avg_max_temperature", models.FloatField()),
                ("avg_min_temperature", models.FloatField()),
                ("total_precipitation", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="weatherdata",
            options={"verbose_name_plural": "WeatherData"},
        ),
        migrations.AlterModelOptions(
            name="yielddata",
            options={"verbose_name_plural": "YieldData"},
        ),
    ]
