# Generated by Django 4.1.4 on 2022-12-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_weatherdatastats_alter_weatherdata_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdatastats",
            name="station_id",
            field=models.CharField(max_length=11),
        ),
    ]
